domain: suite.local
adminEmail: admin@suite.local

apps:
  docs:
    enabled: true
  meet:
    enabled: true
  drive:
    enabled: true
  desk:
    enabled: false
  conversations:
    enabled: false

postgres:
  enabled: true
  host: lasuite-postgresql.lasuite-postgresql.svc.cluster.local
  port: 5432

keycloak:
  enabled: true
  realm: lasuite
  # URL overrides (optional, defaults to auth.{domain})
  externalUrl: ""   # Empty = use auth.{domain}
  backendUrl: ""    # Empty = use internal service (or externalUrl if set)
  testUser:
    enabled: true
    username: user
    email: user@example.com
    password: password

redis:
  enabled: true
  host: redis-master.lasuite-redis.svc.cluster.local
  port: 6379

minio:
  enabled: true

livekit:
  enabled: true

s3:
  provider: minio  # aws | oos | minio
  endpoint: http://minio.lasuite-minio.svc.cluster.local:9000
  host: minio.lasuite-minio.svc.cluster.local
  port: 9000

ingress:
  enabled: true
  className: haproxy

certManager:
  enabled: true

reflector:
  enabled: true

tls:
  issuer: selfsigned

secretSeed: ""
