domain: suite.local
adminEmail: admin@suite.local

apps:
  docs:
    enabled: true
  meet:
    enabled: false
  drive:
    enabled: true
  desk:
    enabled: false
  conversations:
    enabled: false

postgres:
  enabled: true
  host: lasuite-postgresql.lasuite-postgresql.svc.cluster.local
  port: 5432

keycloak:
  enabled: true
  realm: lasuite
  testUser:
    enabled: true
    username: user
    email: user@example.com
    password: password

redis:
  enabled: true
  host: redis-master.lasuite-redis.svc.cluster.local
  port: 6379

minio:
  enabled: true

s3:
  endpoint: http://minio.pa-minio.svc.cluster.local:9000

ingress:
  enabled: true
  className: haproxy

certManager:
  enabled: true

reflector:
  enabled: true

tls:
  issuer: selfsigned

secretSeed: ""
